### ISSUE TITLE
Generate method bindings automatically

### ISSUE THREAD

**Issue by fzyzcjy** [ethanblake4/dart_eval#56] opened 2022-10-19 12:35 UTC
Similar to the issue just now, looking at https://github.com/ethanblake4/dart_eval/pull/36/files I guess things like `String.endsWith` are manually bridged? If so, maybe we can auto generate it. You know, writing down those things by *hand* is very time consuming and error-prone, since we are humans not machines ;)

**Comment by ethanblake4** [comment] 2022-10-19 22:11
Duplicate of https://github.com/ethanblake4/dart_eval/issues/20. Definitely planning on this!

**Closed by ethanblake4** 2022-10-19 22:11 UTC
