### ISSUE TITLE
dart_eval doesn't support external libraries

### ISSUE THREAD

**Issue by kazemcodes** [ethanblake4/dart_eval#101] opened 2023-05-21 05:00 UTC
if it's possible, try to add a way to use external libraries in the dart_eval ( only libraries that are available in the projects pubspec )

**Comment by taosimple** [comment] 2023-05-21 08:00
Use `Bridge` can resolve this issue

**Comment by kazemcodes** [comment] 2023-05-22 04:24
> Use `Bridge` can resolve this issue

Do you mean create a local wrapper around the external library function or classes we want and use that wrapper function in the eval?

**Comment by taosimple** [comment] 2023-05-22 06:14
Yes, using the librarys in a local function and then calling this function through a bridge should work. However, I found that this library has too many bugs and needs to be careful.

**Comment by ethanblake4** [comment] 2023-10-05 21:36
Closing as duplicate of #21

**Closed by ethanblake4** 2023-10-05 21:36 UTC
